### PR TITLE
Upgrade to new mypy

### PR DESCRIPTION
**Pull request by itamarst**
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/4035
Fixes https://tahoe-lafs.org/trac/tahoe-lafs/ticket/3622

### CODE REVIEW

File: src/allmydata/frontends/sftpd.py [hunk 1]
```diff
@@ -1925,7 +1925,11 @@ def writeSequence(self, data):
     def loseConnection(self):
         logmsg("FakeTransport.loseConnection()", level=NOISY)
 
-    # getPeer and getHost can just raise errors, since we don't know what to return
+    def getHost(self):
+        pass
+
+    def getPeer(self):
+        pass
```
Comment (exarkun) [inline src/allmydata/frontends/sftpd.py:1932]: Should we go with ... `raise NotImplementedError()` or something similar here?  I doubt any code was relying on an exception coming out of these before but .... :shrug:

File: src/allmydata/interfaces.py [hunk 2]
```diff
@@ -493,47 +498,6 @@ def get_nickname_for_serverid(serverid):
...
-        """Return a frozenset of (nodeid, service_name, rref) tuples, one
-        for each active connection that provides the given SERVICE_NAME."""
-
-    def get_permuted_peers(service_name, key):
-        """Returns an ordered list of (peerid, rref) tuples, selecting from
-        the connections that provide SERVICE_NAME, using a hash-based
-        permutation keyed by KEY. This randomizes the service list in a
-        repeatable way, to distribute load over many peers.
-        """
-
```
Comment (exarkun) [inline src/allmydata/interfaces.py:536]: Neat!

File: src/allmydata/interfaces.py [hunk 3]
```diff
@@ -551,16 +515,6 @@ class IServer(IDisplayableServer):
...
-    def get_rref():
-        """Obsolete.  Use ``get_storage_server`` instead.
-
-        Once a server is connected, I return a RemoteReference.
-        Before a server is connected for the first time, I return None.
-
-        Note that the rref I return will start producing DeadReferenceErrors
-        once the connection is lost.
-        """
-
```
Comment (exarkun) [inline src/allmydata/interfaces.py:563]: :partying_face:

File: src/allmydata/storage/http_common.py [hunk 4]
```diff
@@ -23,7 +23,7 @@ def get_content_type(headers: Headers) -> Optional[str]:
 
     Returns ``None`` if no content-type was set.
     """
-    values = headers.getRawHeaders("content-type") or [None]
+    values = headers.getRawHeaders("content-type", [None]) or [None]
```
Comment (exarkun) [inline src/allmydata/storage/http_common.py:26]: Oh my, a real bug fix?  Great!

File: src/allmydata/test/cli/test_invite.py [hunk 5]
```diff
@@ -102,18 +102,24 @@ def send_messages(wormhole: IWormhole, messages: Sequence[JSONable]) -> None:
...
     Run two asynchronous functions concurrently and asynchronously return a
     tuple of both their results.
     """
-    return defer.gatherResults([
+    result = defer.gatherResults([
         defer.Deferred.fromCoroutine(client()),
         defer.Deferred.fromCoroutine(server()),
-    ])
-
+    ]).addCallback(tuple)  # type: ignore
```
Comment (exarkun) [inline src/allmydata/test/cli/test_invite.py:121]: The mypy error I see here is:

```
src/allmydata/test/cli/test_invite.py:118:34: error: Argument 1 to "gatherResults" has incompatible type "List[object]"; expected
"Iterable[Deferred[<nothing>]]"  [arg-type]
        result = defer.gatherResults([
                                     ^
```

But I can't figure out why.  `client` and `server` obvious return a type that unifies with the element type of the `Iterable` `gatherResults` accepts...

Any ideas?

File: tox.ini [hunk 6]
```diff
@@ -121,20 +121,18 @@ commands =
 
 [testenv:typechecks]
 basepython = python3
-skip_install = True
 deps =
-    mypy
-    mypy-zope
+    mypy==1.3.0
+    # When 0.9.2 comes out it will work with 1.3, it's just unreleased at the moment...
+    git+https://github.com/shoobx/mypy-zope
```
Comment (exarkun) [inline tox.ini:127]: We could pin a revision here so it doesn't break when they commit something that breaks compatibility with mypy 1.3.0.

File: src/allmydata/storage/lease_schema.py [hunk 7]
```diff
@@ -56,7 +56,7 @@ def _hash_secret(cls, secret):
         """
         Hash a lease secret for storage.
         """
-        return blake2b(secret, digest_size=32, encoder=RawEncoder())
+        return blake2b(secret, digest_size=32, encoder=RawEncoder)
```
Comment (exarkun) [inline src/allmydata/storage/lease_schema.py:59]: Huh this is a little worrying....  I guess it means there are no tests for hashed lease writing?  Or, huh.  It seems to work either way, somehow.  Oh.  because its interface is a staticmethod.  Alrighty then, fine.

**Review by exarkun — APPROVED** [review]
Thanks.  A few minor comments inline.  Please address and merge.

File: src/allmydata/test/cli/test_invite.py (hunk 5 above)
Comment (itamarst) [reply src/allmydata/test/cli/test_invite.py:121]: I saw that, but with some tweaking I also saw another one where the issue was that the result is a list, and Python type checking assumes lists have uniform type. Eventually I gave up because meh, it's a test. But maybe worth filing something upstream.

Comment (itamarst) [reply src/allmydata/test/cli/test_invite.py:121]: Oh, I think it's because of the assumption that list has uniform type, and you're passing list with Deferreds of different types. Filed https://github.com/twisted/twisted/issues/11887
